/*
 * Copyright (C) 2026 by Thun Lu. All rights reserved.
 * Author: Thun Lu <thun.lu@zohomail.cn>
 * Repo:   https://github.com/thun-res/vlink
 *  _    __   __      _           __
 * | |  / /  / /     (_) ____    / /__
 * | | / /  / /     / / / __ \  / //_/
 * | |/ /  / /___  / / / / / / / ,<
 * |___/  /_____/ /_/ /_/ /_/ /_/|_|
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @file pub_sub_fbs.cc
 * @brief DDS-C + FlatBuffers event sample based on an e-commerce user/order schema.
 *
 * The sample focuses on the VLink Event model:
 *   - Publisher<UserT> publishes FlatBuffers Object API values.
 *   - Subscriber<User*> receives zero-copy FlatBuffers pointers.
 *
 * The generated schema lives in fbs/helloworld.fbs and models a nested User ->
 * Profile -> Address / Order / Item structure.
 */

#include <vlink/base/condition_variable.h>
#include <vlink/base/logger.h>
#include <vlink/base/utils.h>
#include <vlink/vlink.h>

#include <atomic>
#include <cstring>
#include <memory>
#include <mutex>
#include <string>

#if __has_include("helloworld.fbs.hpp")
#include "helloworld.fbs.hpp"
#else
#include "helloworld_generated.h"
#endif

using namespace vlink;                 // NOLINT(build/namespaces, google-build-using-namespace)
using namespace std::chrono_literals;  // NOLINT(build/namespaces, google-build-using-namespace)

namespace hw = Helloworld::fbs;

namespace {

constexpr auto kEventUrl = "ddsc://samples/pub_sub_fbs/user";
constexpr uint32_t kPublishIntervalMs = 500U;

const char* safe_c_str(const flatbuffers::String* value) { return value ? value->c_str() : ""; }

std::unique_ptr<hw::ItemT> make_item(const std::string& sku, const std::string& name, float price, int quantity) {
  auto item = std::make_unique<hw::ItemT>();
  item->sku = sku;
  item->name = name;
  item->price = price;
  item->quantity = quantity;
  return item;
}

std::unique_ptr<hw::OrderT> make_order(uint64_t seq) {
  auto order = std::make_unique<hw::OrderT>();
  order->order_id = "ORDER-20260409-" + std::to_string(seq);

  switch (seq % 3) {
    case 1:
      order->status = hw::OrderStatus::Pending;
      break;
    case 2:
      order->status = hw::OrderStatus::Paid;
      break;
    default:
      order->status = hw::OrderStatus::Shipped;
      break;
  }

  order->remark = "generated by sample_pub_sub_fbs";
  order->items.emplace_back(make_item("SKU-" + std::to_string(seq) + "-A", "Mechanical Keyboard", 399.0F, 1));
  order->items.emplace_back(make_item("SKU-" + std::to_string(seq) + "-B", "USB-C Cable", 29.9F, 2));

  float total_price = 0.0F;
  for (const auto& item : order->items) {
    total_price += item->price * static_cast<float>(item->quantity);
  }
  order->total_price = total_price;

  return order;
}

hw::UserT make_user(uint64_t seq) {
  hw::UserT user;
  user.user_id = 10000 + seq;
  user.name = "user_" + std::to_string(seq);
  user.email = "user_" + std::to_string(seq) + "@example.com";

  user.profile = std::make_unique<hw::ProfileT>();
  user.profile->nickname = "buyer_" + std::to_string(seq);
  user.profile->age = static_cast<uint16_t>(20 + seq);
  user.profile->home = std::make_unique<hw::AddressT>();
  user.profile->home->country = "China";
  user.profile->home->city = "Shanghai";
  user.profile->home->street = "Century Avenue No." + std::to_string(seq);
  user.profile->home->zip_code = "200120";
  user.profile->location =
      std::make_unique<hw::Vec2>(121.47F + static_cast<float>(seq) * 0.01F, 31.23F + static_cast<float>(seq) * 0.01F);
  user.profile->tags = {"vip", "flatbuffers", (seq % 2 == 0) ? "web" : "mobile"};

  user.orders.emplace_back(make_order(seq));

  return user;
}

void print_user_summary(const hw::User* user) {
  if (!user) {
    VLOG_W("[Subscriber] null User pointer.");
    return;
  }

  const auto* profile = user->profile();
  const auto* home = profile ? profile->home() : nullptr;
  const auto* location = profile ? profile->location() : nullptr;
  const auto* orders = user->orders();

  // NOLINTNEXTLINE(readability-container-size-empty)
  const auto* first_order = (orders && orders->size() > 0) ? orders->Get(0) : nullptr;
  const auto* items = first_order ? first_order->items() : nullptr;

  VLOG_I("[Subscriber] user_id=", user->user_id(), " name=", safe_c_str(user->name()),
         " email=", safe_c_str(user->email()));

  if (profile) {
    VLOG_I("[Subscriber] nickname=", safe_c_str(profile->nickname()), " age=", profile->age(),
           " city=", home ? safe_c_str(home->city()) : "", " location=(", location ? location->x() : 0.0F, ", ",
           location ? location->y() : 0.0F, ")");
  }

  if (first_order) {
    VLOG_I("[Subscriber] first_order=", safe_c_str(first_order->order_id()),
           " status=", hw::EnumNameOrderStatus(first_order->status()), " total=", first_order->total_price(),
           " item_count=", items ? items->size() : 0);
  }
}

}  // namespace

int run_sub() {
  std::atomic_int received_count{0};

  // Subscriber uses FlatBuffers pointer type, so fields are read directly from
  // the received buffer without unpacking into an intermediate UserT object.
  Subscriber<hw::User*> sub(kEventUrl);
  sub.listen([&received_count](const hw::User* user) {
    int current = received_count.fetch_add(1) + 1;
    VLOG_I("[Subscriber] received #", current);
    print_user_summary(user);
  });

  std::mutex mtx;
  std::unique_lock lock(mtx);
  vlink::condition_variable cv;

  Utils::register_terminate_signal([&cv](int) { cv.notify_one(); });

  VLOG_I("[Subscriber] listening on ", kEventUrl, ", press Ctrl+C to quit.");
  cv.wait(lock);

  VLOG_I("[Subscriber] total received: ", received_count.load());

  return 0;
}

int run_pub() {
  // Publisher uses the Object API type because UserT is easier to construct and
  // VLink will serialize it into FlatBuffers bytes automatically.
  MessageLoop message_loop;
  Utils::register_terminate_signal([&message_loop](int) { message_loop.quit(); });

  Publisher<hw::UserT> pub(kEventUrl);
  uint64_t publish_seq = 0;

  VLOG_I("[Publisher] start timer on ", kEventUrl, ", publish every ", kPublishIntervalMs, "ms, press Ctrl+C to quit.");

  Timer timer;
  timer.attach(&message_loop);
  timer.set_interval(kPublishIntervalMs);
  timer.set_loop_count(Timer::kInfinite);
  timer.start([&pub, &publish_seq]() {
    ++publish_seq;
    auto user = make_user(publish_seq);
    bool ok = pub.publish(user);

    VLOG_I("[Publisher] published #", publish_seq, " user_id=", user.user_id, " name=", user.name, " ok=", ok);
  });

  message_loop.run();

  timer.stop();
  VLOG_I("[Publisher] total published: ", publish_seq);
  return 0;
}

int main(int argc, char* argv[]) {
  if (argc == 2 && std::strcmp(argv[1], "sub") == 0) {
    return run_sub();
  }

  if (argc == 2 && std::strcmp(argv[1], "pub") == 0) {
    return run_pub();
  }

  VLOG_I("Usage:");
  VLOG_I(" sample_pub_sub_fbs sub");
  VLOG_I(" sample_pub_sub_fbs pub");

  return 1;
}
